### ISSUE TITLE
Server-Error due to "call to undefined function" and plugin causing Server_error 500 as well

### ISSUE THREAD

**Issue by mamorg79** [ip2location/ip2location-piwik#35]
Hi,

Since a few month we are receiving ServerError 500 when using the following URL:

https://piwik.re-in.de/matomo.php?action_name=voelkner%20-%20direkt%20günstiger%20|%20Elektronik%2C%20Technik%2C%20Werkzeug%20%26%20mehr&idsite=1&rec=1&r=858341&h=9&m=17&s=58&url=https%3A%2F%2Fwww.voelkner.de%2Fmy%2Forders_details.html%3Foid%3D159189407%26page%3D1&urlref=https%3A%2F%2Fwww.voelkner.de%2Fmy%2Forders.html&uid=135003855&_id=0e560923070c321a&_idts=1587712534&_idvc=1&_idn=0&_refts=0&_viewts=1587712534&send_image=1&pdf=0&qt=0&realp=0&wma=0&dir=0&fla=0&java=0&gears=0&ag=0&cookie=1&res=1920x1080&_cvar={"1"%3A["B2"%2C"3"]%2C"2"%3A["0"%2C"1"]%2C"3"%3A["WKDB"%2C"0"]%2C"4"%3A["usr"%2C"QYSVVYCSS"]%2C"5"%3A["1"%2C"0"]}&gt_ms=680&pv_id=2dAjC3

I could track down the issue to:

`#0 /var/www/html/plugins/IP2Location/lib/IP2Location.php(1617): IP2Location\Database::ipVersionAndNumber('2a01:c22:7640:5...')
#1 /var/www/html/plugins/IP2Location/LocationProvider/IP2Location.php(92): IP2Location\Database->lookup('2a01:c22:7640:5...', 1001)
#2 /var/www/html/plugins/UserCountry/VisitorGeolocator.php(145): Piwik\Plugins\IP2Location\LocationProvider\IP2Location->getLocation(Array)
#3 /var/www/html/plugins/UserCountry/VisitorGeolocator.php(115): Piwik\Plugins\UserCountry\VisitorGeolocator->getLocationObject(Object(Piwik\Plugins\IP2Location\LocationProvider\IP2Location), Array)
#4 /var/www/html/plugins/UserCountry/Columns/Base.php(55): Piwik\Plugins\UserCountry\VisitorGeolocator->getLocation(Array, true)
#5 /var/www/html/plugins/UserCountry/Columns/City.php(43): Piwik\Plugins\UserCountry\Columns\Base->getLocationDetail(Array, 'city_name')
#6 /var/www/html/core/Tracker/Visit.php(482): Piwik\Plugins\UserCountry\Columns\City->onNewVisit(Object(Piwik\Tracker\Request), Object(Piwik\Tracker\Visitor), Object(Piwik\Tracker\ActionPageview))
#7 /var/www/html/core/Tracker/Visit.php(288): Piwik\Tracker\Visit->triggerHookOnDimensions(Array, 'onNewVisit')
#8 /var/www/html/core/Tracker/Visit.php(203): Piwik\Tracker\Visit->handleNewVisit(NULL)
#9 /var/www/html/core/Tracker.php(155): Piwik\Tracker\Visit->handle()
#10 /var/www/html/core/Tracker/Handler.php(57): Piwik\Tracker->trackRequest(Object(Piwik\Tracker\Request))
#11 /var/www/html/core/Tracker.php(135): Piwik\Tracker\Handler->process(Object(Piwik\Tracker), Object(Piwik\Tracker\RequestSet))
#12 /var/www/html/core/Tracker.php(112): Piwik\Tracker->track(Object(Piwik\Tracker\Handler), Object(Piwik\Tracker\RequestSet))
#13 /var/www/html/piwik.php(76): Piwik\Tracker->main(Object(Piwik\Tracker\Handler), Object(Piwik\Tracker\RequestSet))
#14 {main}`

as well as the errors above due to debugging I get an error message when I try to connect to my matomo instance inside EDGE Browser. The error occurs as follows:

![image](https://user-images.githubusercontent.com/24877285/81003360-0ec98280-8e4b-11ea-86c6-3285a9387036.png)

Maybee you could take care for this.

Regards, Marcel

**Comment by mamorg79** [comment]
Hello everyone.

Due to help of Matomo, we could figure out that the problem was already resolved like in the following issue:

[https://github.com/ip2location/ip2location-piwik/issues/20](https://github.com/ip2location/ip2location-piwik/issues/20)

Regards, Marcel
